-- user
create table public.user(
    id int generated by default as identity,
    nama text not null,
    email text not null,
    password text not null ,
    sex text mot null,
    alamat text not null,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone

);
alter table only public.user add constraint user_pkey primary key(id);

insert into user(nama, email, password, sex, alamat) VALUES
    ('fahmi Prasetio', 'fahmi@gmail.com', '123123', 'Pria', 'Bandung'),
    ('Cecep Ahmad Fauzi', 'Cecep@gmail.com', '123123', 'Pria', "Sumedang")



-- Table Barang/produk 
create table public.daftar_barang(
    id_barang int generated by default as identity,
    nama_barang text not null,
    jumlah int not null,
    satuan text not null,
    harga_beli int not null,
    harga_jual int not null
)
alter table only public.daftar_barang add constraint daftar_barang_pkey primary key(id_barang);

insert into daftar_barang(id_barang,nama_barang,jumlah,satuan,harga_beli,harga_jual) VALUES
    (20182601,'Kemeja Putih',100, "pcs", 75000, 100000),
    (20182602,'Celana Chinos',50, "pcs", 65000, 70000),
    (20182601,'Jacket Hodie',45, "pcs", 110000, 150000)

